#!/bin/bash

CONFIG_FILE_NAME=".zshrc"
CONFIG_FOLDER_NAME="zsh"

# APT installation -------------------------------------------------------------
if [ ! -f /usr/bin/zsh ]; then
  sudo apt install zsh
else
  echo "zsh already installed"
fi

# Oh My Zsh installation -------------------------------------------------------
if [ ! -d ${ZSH:-~/.oh-my-zsh} ]; then
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
  echo "Oh-My-Zsh already installed"
fi

# Plugins config ---------------------------------------------------------------
# zsh autosuggestions
if [ ! -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions ]; then
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
fi

# zsh syntax highlighting
if [ ! -d ${ZSH:-~/.oh-my-zsh}/plugins/zsh-syntax-highlighting ]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH:-~/.oh-my-zsh}/plugins/zsh-syntax-highlighting
fi

# zsh completions
if [ ! -d ${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions ]; then
  git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions
fi

# Spaceship theme --------------------------------------------------------------
if [ ! -d ${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/themes/spaceship-prompt ]; then
  git clone https://github.com/spaceship-prompt/spaceship-prompt.git ${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/themes/spaceship-prompt --depth=1
fi
if [ ! -f ${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/themes/spaceship.zsh-theme ]; then
  ln -s ${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/themes/spaceship-prompt/spaceship.zsh-theme ${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/themes/spaceship.zsh-theme
fi

. $WSL_CONFIG_HOME/wsl-substitute-config $CONFIG_FOLDER_NAME $CONFIG_FILE_NAME
